# Create User
POST http://localhost:3000/user
Content-Type: application/json

{ 
    "username": "demo2",
    "password": "demo2"
}

# Update User
# POST http://localhost:3000/user/12
# Content-Type: application/json

# {
#     "username": "updateTest12",
#     "password": "newPassword"
# }

# Delete User
//DELETE http://localhost:3000/user/1